config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    resources :reviews
    resources :likes
  end
  resources :users

  get 'signup' => "users#new"
  get 'signin' => "sessions#new"
  resources :categories
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :badgeable, polymorphic: true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :posts, through: :categorizations

  validates :name, presence: true, uniqueness: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :set_slug

  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :badges, as: :badgeable

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :title, :description, presence: true

  def to_param
    slug
  end

  private
    def set_slug
      self.slug = title.parameterize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post   

  has_many :badges, as: :badgeable
  
  has_secure_password
  
  validates :name, presence: true
  validates :username, format: { with: /\A[A-Z0-9]+\z/i }, uniqueness: { case_sensitive: false }, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 10, allow_blank: true }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_signin

  def create
    @post = Post.find_by!(slug: params[:post_id])
    @post.likes.create!(user: current_user)
    redirect_to @post
  end

  def destroy
    like = current_user.likes.find(params[:id])
    like.destroy
    @post = Post.find_by!(slug: params[:post_id])
    redirect_to @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  #before_action :require_admin, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @likers = @post.likers
    @categories = @post.categories
    @badges = @post.badges

    if current_user
    @like = current_user.likes.find_by(post_id: @post.id)
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated!"
      redirect_to post_path
    else
      render :edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to @post
    else
      render :new
    end 
  end

  def destroy
    @post.destroy
    flash[:alert] = "Post successfully deleted!"
    redirect_to root_path
  end


  private
    def post_params
      params.require(:post).permit(:title, :description, category_ids: [])
    end

    def set_post
      @post = Post.find_by!(slug: params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_signin
  before_action :set_post

  def index
    @reviews = @post.reviews.order("created_at DESC")
  end

  def new
    @review = @post.reviews.new
  end

  def create
    @review = @post.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      redirect_to post_reviews_path(@post), notice: "Comment posted!"
    else
      render :new
    end
  end


  private 
    def review_params
      params.require(:review).permit(:comment, :like)
    end
    
    def set_post
      @post = Post.find_by!(slug: params[:post_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email_or_username]) || User.find_by(username: params[:email_or_username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), notice: "Welcome back, #{user.name}"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end 
  end 

  def destroy
    session[:user_id] = nil
    redirect_to posts_url, notice: "You are now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @liked_posts = @user.liked_posts
    @badges = @user.badges
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "You are now registered in Šaušikebana!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    redirect_to root_url, alert: "Account successfully deleted!"
  end

  private
  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation, :username)
  end

  def require_correct_user
    @user = User.find(params[:id])
      redirect_to posts_url unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_or_unlike_button(post, like)
    if like
      button_to "Unlike", post_like_path(post, like), method: :delete, class: "unlike-button"
    else
      button_to "Like", post_likes_path(post), class: "like-button"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sausikebana</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6974d2f75b.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "partials/header" %>
      <div class="container content">
        <%= render "partials/flash" %>
        <%= yield %>
      </div>
    <%= render "partials/footer" %>
    
  </body>
</html>

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <div class="container footer">
    <small>Copyright &copy; Luka Matuzić</small>
  </div>
</footer>

app/views/partials/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light ">
  <%= link_to 'Kurcina jebo te bog', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-hamburger"></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to current_user.name, current_user %>     
        </li>

        <li class="nav-item">
         <%= link_to "Account Settings", edit_user_path(current_user) %>
        </li>

         <li class="nav-item">
            <%= link_to "Sign out", session_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", signin_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
</header>