config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    resources :reviews
    resources :likes
  end
  resources :users

  get 'signup' => "users#new"
  get 'signin' => "sessions#new"
  resources :categories
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :badgeable, polymorphic: true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :posts, through: :categorizations

  validates :name, presence: true, uniqueness: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :set_slug

  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :badges, as: :badgeable

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :title, :description, presence: true

  def to_param
    slug
  end

  private
    def set_slug
      self.slug = title.parameterize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post   

  has_many :badges, as: :badgeable
  
  has_secure_password
  
  validates :name, presence: true
  validates :username, format: { with: /\A[A-Z0-9]+\z/i }, uniqueness: { case_sensitive: false }, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 10, allow_blank: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private 
  #allows all CONTROLLERS to get access to this method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  #allows all VIEWS to get access to the current_user
  helper_method :current_user
  
  def current_user?(user)
    current_user == user
  end
  helper_method :current_user?


  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in first!"
    end
  end
  

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access!"
    end
  end
  
  def current_user_admin?
    current_user && current_user.admin?
  end
  helper_method :current_user_admin?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_signin

  def create
    @post = Post.find_by!(slug: params[:post_id])
    @post.likes.create!(user: current_user)
    redirect_to @post
  end

  def destroy
    like = current_user.likes.find(params[:id])
    like.destroy
    @post = Post.find_by!(slug: params[:post_id])
    redirect_to @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  #before_action :require_admin, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @likers = @post.likers
    @categories = @post.categories
    @badges = @post.badges

    if current_user
    @like = current_user.likes.find_by(post_id: @post.id)
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated!"
      redirect_to post_path
    else
      render :edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to @post
    else
      render :new
    end 
  end

  def destroy
    @post.destroy
    flash[:alert] = "Post successfully deleted!"
    redirect_to root_path
  end


  private
    def post_params
      params.require(:post).permit(:title, :description, category_ids: [])
    end

    def set_post
      @post = Post.find_by!(slug: params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_signin
  before_action :set_post

  def index
    @reviews = @post.reviews.order("created_at DESC")
  end

  def new
    @review = @post.reviews.new
  end

  def create
    @review = @post.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      redirect_to post_reviews_path(@post), notice: "Comment posted!"
    else
      render :new
    end
  end


  private 
    def review_params
      params.require(:review).permit(:comment, :like)
    end
    
    def set_post
      @post = Post.find_by!(slug: params[:post_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email_or_username]) || User.find_by(username: params[:email_or_username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), notice: "Welcome back, #{user.name}"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end 
  end 

  def destroy
    session[:user_id] = nil
    redirect_to posts_url, notice: "You are now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @liked_posts = @user.liked_posts
    @badges = @user.badges
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "You are now registered in Šaušikebana!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    redirect_to root_url, alert: "Account successfully deleted!"
  end

  private
  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation, :username)
  end

  def require_correct_user
    @user = User.find(params[:id])
      redirect_to posts_url unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_or_unlike_button(post, like)
    if like
      button_to "Unlike", post_like_path(post, like), method: :delete, class: "unlike-button"
    else
      button_to "Like", post_likes_path(post), class: "like-button"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<div class="edit-form">
  <h4>Editing: <%= @post.title %></h4>

  <%= bootstrap_form_with(model: @post, local: true, class: "form") do |f| %>
    <%= f.text_field :title, autofocus: true %>
    <%= f.text_area :description, rows: 10 %>
        <div class="checkboxes">
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
    </div>
    <%= f.submit 'Update', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="posts">
  <h3>Posts</h3>
  <% @posts.each do |post| %>
    <div class="post">
      <h5><%= link_to(post.title, post_path(post), class: "post-title") %></h5>
      <div class="post-description"><%= post.description %></div>

      <div class="comments">
        <%= link_to pluralize(post.reviews.size, "Comment"), post_reviews_path(post) %>
        <%= link_to "New Comment", new_post_review_path(post) %>
      </div>
    </div>
  <% end %> 

  <div class="new_post_button">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container new_post">
  <h3>Create new post</h3>

  <%= bootstrap_form_with(model: @post, local: true, class: "form") do |f| %>
    <%= f.text_field :title, autofocus: true %>
    <%= f.text_area :description, rows: 5 %>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, class: "dropdown") %>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-details">
  <div class="post-info">
    <div class="post-title">
      <h5><%= @post.title %></h5>
    </div>

    <div class="post-description">
      <%= @post.description %>
    </div>

    <% if @badges.present? %>
      <div class="post-badge-container">
        <h5 class="badges-title">Badges</h5>
        <% @post.badges.each do |badge| %>
          <div class="post-badge">
            <%= badge.body %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if current_user %>
    <div class="likes">
      <%= like_or_unlike_button(@post, @like) %>
      <div class="likes-count">
        <i class="far fa-thumbs-up"></i> <%= @likers.size %>
      </div>
    </div>
  <% end %>


  <div class="liked-by">
    <% if @likers.present? %>
      Liked by:
        <% @likers.each do |user| %>
          <%= link_to user.name, user %>
        <% end %>
    <% end %>
  </div>

  <% if @categories.present? %>
    <div class="post-categories">
      <h5>Categories</h5>
      <ul class="categories">
        <% @categories.each do |c| %>
          <li>
            <%= c.name %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class="admin">
  <% if current_user_admin? %>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<div class="reviews">
<h5>Comments for <%= link_to @post.title, @post %></h5>
  <% @reviews.each do |review| %>
    <div class="review">
      <strong><%= link_to review.user.name, review.user %></strong>
      "<%= review.comment %>"
      <br>
      <span class="member-since"><%= time_ago_in_words(review.created_at) %> ago</span>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container new-comment">
  <h5>New comment for <%= link_to @post.title, post_path(@post) %></h5>

  <%= bootstrap_form_with(model: [@post, @review], local: true, class: "form") do |f| %>
    <%= f.text_area :comment, rows: 10 %>
    <%= f.submit "Post Comment" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="edit-form">
  <h5>Edit account</h5>
  <%= bootstrap_form_with(model: @user, local: true, class: "form") do |f| %>
    <%= f.text_field :name, autofocus: true %>
    <%= f.text_field :username%>
    <%= f.email_field :email %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Edit account" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="users">
  <h5 class="users-title">Users total: <%= @users.size %></h5>
  <% @users.each do |user| %>
    <div class="user">
      <strong><%= link_to user.name, user %></strong>
      Član od: <%= user.created_at.strftime("%d.%m.%Y.") %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="edit-form">
  <h5>Sign Up</h5>
  <%= bootstrap_form_with(model: @user, local: true, class: "form") do |f| %>
    <%= f.text_field :name, autofocus: true %>
    <%= f.text_field :username%>
    <%= f.email_field :email %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign Up" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div><%= @user.name %></div>
  <div><%= mail_to(@user.email) %></div>

  <% if @badges.present? %>
    <div class="post-badge-container">
      <h5>Interests</h5>
      <% @user.badges.each do |badge| %>
        <div class="post-badge">
          <%= badge.body %>
        </div>
      <% end %>
    </div>
    <% end %>

  <% if @reviews.present? %>
    <h5>Commented posts</h5>
    <% @reviews.each do |review| %>
      <div class="commented-posts">
        <div class="commented-post">
          <%= link_to review.post.title, review.post %>
        </div>

        <div class="date">
          <%= time_ago_in_words(review.created_at) %> ago
        </div>
      </div>
    <% end %>
  <% end %>

  <% if @liked_posts.present? %>
    <div class="liked-posts">
      <h5>Liked posts</h5>
      <% @liked_posts.each do |post| %>
        <%= link_to post.title, post %>
      <% end %>
    </div>
  <% end %>

  <% if current_user?(@user) %>
    <div class="actions">
      <%= link_to "Edit account", edit_user_path(@user), class: "btn btn-primary" %>

      <% if current_user_admin? %>
        <%= link_to "Delete account", user_path(@user), method: :delete,
                    data: { confirm: "Are you sure you want to delete this account?" },
                    class: "btn btn-danger" %>
      <% end %>
    </div>
  <% end %>
</div>